### ISSUE TITLE
Swap-able storage.

### ISSUE THREAD

**Issue by ademgashi** [mwijnands/PluploadMvc#16]
Hi @mwijnands I hope this message finds you well with everything.
Kudos for the great work you have done with this project.

I was wondering if you plan to have different storage options, so for example someone that wants to save files on s3 amazon making it somehow easy to do this with the wrapper?

**Comment by ademgashi** [comment]
bump

**Comment by mwijnands** [comment]
Hi @ademgashi PluploadMvc is a component to make it easier to work with file uploading using Plupload in ASP.NET MVC. If you want to save files somewhere, then just do that in your controller or wherever. S3 Amazon probably has the docs on how to do that. It will never be a feature of this PluploadMvc as that would be... weird.

**Comment by ademgashi** [comment]
Thank you. I just thought tha everyone would love having something like thishttp://www.plupload.com/docs/Upload-to-Amazon-S3

**Comment by ademgashi** [comment]
Thank you. I just thought tha everyone would love having something like this http://www.plupload.com/docs/Upload-to-Amazon-S3
